# Generated by Django 4.2.2 on 2023-06-28 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO vacancies_company (name) VALUES ('Kolesa Group');"
        )
    ]
